/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package fr.viteducode.kafkaclient.producer.simple.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CompanieValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -434631368872722630L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CompanieValue\",\"namespace\":\"fr.viteducode.kafkaclient.producer.simple.data\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"country\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"sales\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"profit\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CompanieValue> ENCODER =
      new BinaryMessageEncoder<CompanieValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CompanieValue> DECODER =
      new BinaryMessageDecoder<CompanieValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CompanieValue> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CompanieValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CompanieValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CompanieValue>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CompanieValue to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CompanieValue from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CompanieValue instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CompanieValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String name;
  private java.lang.String country;
  private java.lang.String sales;
  private java.lang.String profit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CompanieValue() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param country The new value for country
   * @param sales The new value for sales
   * @param profit The new value for profit
   */
  public CompanieValue(java.lang.String name, java.lang.String country, java.lang.String sales, java.lang.String profit) {
    this.name = name;
    this.country = country;
    this.sales = sales;
    this.profit = profit;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return country;
    case 2: return sales;
    case 3: return profit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: country = value$ != null ? value$.toString() : null; break;
    case 2: sales = value$ != null ? value$.toString() : null; break;
    case 3: profit = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.String getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.String value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'sales' field.
   * @return The value of the 'sales' field.
   */
  public java.lang.String getSales() {
    return sales;
  }


  /**
   * Sets the value of the 'sales' field.
   * @param value the value to set.
   */
  public void setSales(java.lang.String value) {
    this.sales = value;
  }

  /**
   * Gets the value of the 'profit' field.
   * @return The value of the 'profit' field.
   */
  public java.lang.String getProfit() {
    return profit;
  }


  /**
   * Sets the value of the 'profit' field.
   * @param value the value to set.
   */
  public void setProfit(java.lang.String value) {
    this.profit = value;
  }

  /**
   * Creates a new CompanieValue RecordBuilder.
   * @return A new CompanieValue RecordBuilder
   */
  public static fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder newBuilder() {
    return new fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder();
  }

  /**
   * Creates a new CompanieValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CompanieValue RecordBuilder
   */
  public static fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder newBuilder(fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder other) {
    if (other == null) {
      return new fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder();
    } else {
      return new fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder(other);
    }
  }

  /**
   * Creates a new CompanieValue RecordBuilder by copying an existing CompanieValue instance.
   * @param other The existing instance to copy.
   * @return A new CompanieValue RecordBuilder
   */
  public static fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder newBuilder(fr.viteducode.kafkaclient.producer.simple.data.CompanieValue other) {
    if (other == null) {
      return new fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder();
    } else {
      return new fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder(other);
    }
  }

  /**
   * RecordBuilder for CompanieValue instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CompanieValue>
    implements org.apache.avro.data.RecordBuilder<CompanieValue> {

    private java.lang.String name;
    private java.lang.String country;
    private java.lang.String sales;
    private java.lang.String profit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.country)) {
        this.country = data().deepCopy(fields()[1].schema(), other.country);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.sales)) {
        this.sales = data().deepCopy(fields()[2].schema(), other.sales);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.profit)) {
        this.profit = data().deepCopy(fields()[3].schema(), other.profit);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CompanieValue instance
     * @param other The existing instance to copy.
     */
    private Builder(fr.viteducode.kafkaclient.producer.simple.data.CompanieValue other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.country)) {
        this.country = data().deepCopy(fields()[1].schema(), other.country);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sales)) {
        this.sales = data().deepCopy(fields()[2].schema(), other.sales);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.profit)) {
        this.profit = data().deepCopy(fields()[3].schema(), other.profit);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.String getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder setCountry(java.lang.String value) {
      validate(fields()[1], value);
      this.country = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder clearCountry() {
      country = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sales' field.
      * @return The value.
      */
    public java.lang.String getSales() {
      return sales;
    }


    /**
      * Sets the value of the 'sales' field.
      * @param value The value of 'sales'.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder setSales(java.lang.String value) {
      validate(fields()[2], value);
      this.sales = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sales' field has been set.
      * @return True if the 'sales' field has been set, false otherwise.
      */
    public boolean hasSales() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sales' field.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder clearSales() {
      sales = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'profit' field.
      * @return The value.
      */
    public java.lang.String getProfit() {
      return profit;
    }


    /**
      * Sets the value of the 'profit' field.
      * @param value The value of 'profit'.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder setProfit(java.lang.String value) {
      validate(fields()[3], value);
      this.profit = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'profit' field has been set.
      * @return True if the 'profit' field has been set, false otherwise.
      */
    public boolean hasProfit() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'profit' field.
      * @return This builder.
      */
    public fr.viteducode.kafkaclient.producer.simple.data.CompanieValue.Builder clearProfit() {
      profit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CompanieValue build() {
      try {
        CompanieValue record = new CompanieValue();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.country = fieldSetFlags()[1] ? this.country : (java.lang.String) defaultValue(fields()[1]);
        record.sales = fieldSetFlags()[2] ? this.sales : (java.lang.String) defaultValue(fields()[2]);
        record.profit = fieldSetFlags()[3] ? this.profit : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CompanieValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<CompanieValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CompanieValue>
    READER$ = (org.apache.avro.io.DatumReader<CompanieValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    if (this.country == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.country);
    }

    if (this.sales == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.sales);
    }

    if (this.profit == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.profit);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.country = null;
      } else {
        this.country = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.sales = null;
      } else {
        this.sales = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.profit = null;
      } else {
        this.profit = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.country = null;
          } else {
            this.country = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sales = null;
          } else {
            this.sales = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.profit = null;
          } else {
            this.profit = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










